modules:
  http_2xx:
    prober: http
    timeout: 60s
    http:
      headers:
        health_check: prometheus
      no_follow_redirects: false
      preferred_ip_protocol: ip4
      # valid_status_codes: [] # 2xx
      method: GET
